### ISSUE TITLE
Information pop-up "Redirection Failed'

### ISSUE THREAD

**Issue by matthPAI** [derricksmith/phpsaml#83] opened 2022-05-23 08:00 UTC
Hello,
I have an issue that I can't really solve, I have no log when the message appears.

When I connect with an account via the password of the internal base of GLPI, no message.

When I use the SSO, it connects without problems but displays a small pop-up in the bottom right corner telling me "redirection failed".

![image](https://user-images.githubusercontent.com/106062556/169771939-9c2599e5-c006-4b51-bd05-596643c89bf3.png)

As I said, I have no log, the only information I found is that the message is generated by GLPI, by the file glpi/srv/Toolbox.php, line 1511.

I am in version 9.5.7

Thank you for your work, the result is great !

**Comment by chris-gralike-AMIS** [comment] 2022-07-25 20:27
This is caused by a $_SERVER property that also passes the connection port in the url. I.e https://somehost.domain.tld:443/. A fix for this has been provided in a PR.

**Comment by derricksmith** [comment] 2022-07-25 20:53
Fixed by #95

**Comment by derricksmith** [comment] 2022-11-17 03:30
Fixed in 1.2.1

**Closed by derricksmith** 2022-11-17 03:30 UTC
