### ISSUE TITLE
Azure AD - Guest User using OneTimePassCode

### ISSUE THREAD

**Issue by pablitobin** [derricksmith/phpsaml#21] opened 2020-10-15 20:21 UTC
If a azure AD user (guest) try to login using SAML, Microsoft sends a passcode by email to login (not password).. When it is entered to login, authentication fails.

![image](https://user-images.githubusercontent.com/40396227/96181783-2331a100-0efa-11eb-9218-c8c736c18a4a.png)

**Comment by derricksmith** [comment] 2020-10-15 21:14
AADSTS75011: Authentication method ‘X509, MultiFactor’ by which the user authenticated with the service doesn’t match requested authentication method ‘Password, ProtectedTransport’. Contact the Lever application owner – Usually this is caused by the fact that the SAML application is specifying the RequestedAuthContext with the Comparison attribute set to “exact” in SAML request sent to Azure AD.  - https://s4erka.wordpress.com/2020/07/24/aadsts-azure-ad-sign-in-errors/

Looks like there is a way to configure this per the php-saml settings but will take some time for me to test.  

![image](https://user-images.githubusercontent.com/7143479/96186653-fdf06300-0ef8-11eb-88bf-317cbaf6d07e.png)

**Comment by pablitobin** [comment] 2020-10-16 02:34
may be this works

https://github.com/onelogin/python-saml/issues/212

**Comment by pablitobin** [comment] 2020-10-28 19:03
Hi Derrick, do you have any update?

**Comment by derricksmith** [comment] 2020-11-05 16:02
I have not had time to address this.  The end of year is busy for me.  I will address asap.

**Comment by derricksmith** [comment] 2020-11-14 00:23
can you confirm the following addition resolves the issue?


// append to end of lib\php-saml\settings.php

    // Security settings
    'security' => array (
        'requestedAuthnContext' => false
    )

**Comment by derricksmith** [comment] 2021-01-28 05:41
Resolved in release 1.1.0.  I added AuthN settings to the plugin configuration page.  Please test new version when possible.

**Closed** 2021-03-25 15:15 UTC
Labels: bug, enhancement
